import express from "express";
import { chromium } from "playwright";

const app = express();
app.use(express.json({ limit: "5mb" }));

const PORT = process.env.PORT || 8080;
const API_SECRET = process.env.PDF_WORKER_SECRET || "dev-secret";

/** Health check */
app.get("/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

/**
 * POST /render-pdf
 * Body: { html: string, options?: { format?, landscape?, margin? } }
 * Returns: PDF binary
 */
app.post("/render-pdf", async (req, res) => {
  // Validate secret
  const authHeader = req.headers.authorization;
  if (authHeader !== `Bearer ${API_SECRET}`) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  const { html, options = {} } = req.body;
  if (!html || typeof html !== "string") {
    return res.status(400).json({ error: "html field is required" });
  }

  let browser = null;
  try {
    browser = await chromium.launch({
      args: ["--no-sandbox", "--disable-dev-shm-usage"],
    });
    const page = await browser.newPage();

    // Set content with CJK-friendly base styles
    await page.setContent(
      `<!DOCTYPE html>
      <html lang="zh-TW">
      <head>
        <meta charset="UTF-8">
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;500;700&display=swap');
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: 'Noto Sans TC', 'PingFang TC', 'Microsoft JhengHei', sans-serif;
            font-size: 14px;
            line-height: 1.6;
            color: #1a1a1a;
            padding: 40px;
          }
          h1 { font-size: 24px; font-weight: 700; margin-bottom: 16px; }
          h2 { font-size: 20px; font-weight: 700; margin-bottom: 12px; color: #333; }
          h3 { font-size: 16px; font-weight: 600; margin-bottom: 8px; }
          p { margin-bottom: 8px; }
          table { width: 100%; border-collapse: collapse; margin: 12px 0; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
          th { background: #f5f5f5; font-weight: 600; }
          .chart-placeholder { background: #f0f0f0; padding: 20px; text-align: center; color: #666; border-radius: 8px; margin: 12px 0; }
          .source { font-size: 11px; color: #666; border-top: 1px solid #eee; padding-top: 8px; margin-top: 16px; }
          .footer { position: fixed; bottom: 20px; right: 40px; font-size: 10px; color: #999; }
        </style>
      </head>
      <body>${html}<div class="footer">Generated by RagicEDP AI Expert</div></body>
      </html>`,
      { waitUntil: "networkidle" }
    );

    const pdfBuffer = await page.pdf({
      format: options.format || "A4",
      landscape: options.landscape || false,
      printBackground: true,
      margin: options.margin || {
        top: "20mm",
        bottom: "20mm",
        left: "15mm",
        right: "15mm",
      },
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", 'attachment; filename="report.pdf"');
    res.send(pdfBuffer);
  } catch (err) {
    console.error("PDF generation failed:", err);
    res.status(500).json({ error: "PDF generation failed" });
  } finally {
    if (browser) await browser.close();
  }
});

app.listen(PORT, () => {
  console.log(`PDF Worker listening on port ${PORT}`);
});
